name: firebase_ml_demo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0+1

  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_functions: ^3.0.2

  gap: ^2.0.0
  image_picker: ^0.8.3+3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
